import { Question } from "../../types";

const questions: Question[] = [
  {
    id: 5,
    enunciado:
      "Durante una partida de Brawl Stars, mi Brawler ha perdido un 20% de su salud tras un ataque enemigo. Si tenía 400 de salud, ¿cuánta salud le queda ahora?",
    enunciadoFeedback: `Durante una partida de Brawl Stars, mi Brawler ha <span style="color: red;">PERDIDO</span> un <span style="color: red;">20%</span> de su salud tras un ataque enemigo. Si tenía <span style="color: red;">400</span> de salud, ¿cuánta salud le queda <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! ",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay una disminución de salud.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "¡Correcto! La salud ha disminuido.",
      feedbackIncorrecto: "Incorrecto. No estamos aumentando la salud.",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "400",
        "20",
        "400",
        "100",
        "400",
        "8000",
        "100",
        "400",
        "80",
        "320",
      ],
    },
  },
  {
    id: 6,
    enunciado:
      "En una partida de Brawl Stars, mi Brawler ha perdido un 25% de su munición después de un intenso combate. Si tenía 120 balas, ¿cuántas balas le quedan ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, mi Brawler ha <span style="color: red;">PERDIDO</span> un <span style="color: red;">25%</span> de su munición después de un intenso combate. Si tenía <span style="color: red;">120</span> balas, ¿cuántas balas le quedan <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! ",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay una disminución de munición.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "¡Correcto! La munición ha disminuido.",
      feedbackIncorrecto: "Incorrecto. No estamos aumentando la munición.",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "120",
        "25",
        "120",
        "100",
        "120",
        "3000",
        "100",
        "120",
        "30",
        "90",
      ],
    },
  },
  {
    id: 7,
    enunciado:
      "En una partida de Brawl Stars, mi Brawler ha perdido un 30% de su velocidad tras recibir un golpe. Si tenía 200 de velocidad, ¿cuánta velocidad le queda ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, mi Brawler ha <span style="color: red;">PERDIDO</span> un <span style="color: red;">30%</span> de su velocidad tras recibir un golpe. Si tenía <span style="color: red;">200</span> de velocidad, ¿cuánta velocidad le queda <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! ",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay una disminución de velocidad.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "¡Correcto! La velocidad ha disminuido.",
      feedbackIncorrecto: "Incorrecto. No estamos aumentando la velocidad.",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "200",
        "30",
        "200",
        "100",
        "200",
        "6000",
        "100",
        "200",
        "60",
        "140",
      ],
    },
  },
  {
    id: 8,
    enunciado:
      "En una partida de Brawl Stars, mi Brawler ha perdido un 5% de su daño por segundo tras un ataque especial. Si hacía 150 de daño por segundo, ¿cuánto daño hace ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, mi Brawler ha <span style="color: red;">PERDIDO</span> un <span style="color: red;">5%</span> de su daño por segundo tras un ataque especial. Si hacía <span style="color: red;">150</span> de daño por segundo, ¿cuánto daño hace <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! ",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay una disminución de daño.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "¡Correcto! El daño ha disminuido.",
      feedbackIncorrecto: "Incorrecto. No estamos aumentando el daño.",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "150",
        "5",
        "150",
        "100",
        "150",
        "750",
        "100",
        "150",
        "7.5",
        "142.5",
      ],
    },
  },
  {
    id: 9,
    enunciado:
      "En una partida de Brawl Stars, mi Brawler ha perdido un 40% de su escudo tras un ataque. Si tenía 500 de escudo, ¿cuánto escudo le queda ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, mi Brawler ha <span style="color: red;">PERDIDO</span> un <span style="color: red;">40%</span> de su escudo tras un ataque. Si tenía <span style="color: red;">500</span> de escudo, ¿cuánto escudo le queda <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! ",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay una disminución de escudo.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "¡Correcto! El escudo ha disminuido.",
      feedbackIncorrecto: "Incorrecto. No estamos aumentando el escudo.",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "500",
        "40",
        "500",
        "100",
        "500",
        "20000",
        "100",
        "500",
        "200",
        "300",
      ],
    },
  },
  {
    id: 4,
    enunciado:
      "En una partida de Brawl Stars, mi Brawler ha perdido un 15% de su energía después de recibir daño. Si tenía 300 de energía, ¿cuánta energía le queda ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, mi Brawler ha <span style="color: red;">PERDIDO</span> un <span style="color: red;">15%</span> de su energía después de recibir daño. Si tenía <span style="color: red;">300</span> de energía, ¿cuánta energía le queda <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay una disminución de energía.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "¡Correcto! La energía ha disminuido.",
      feedbackIncorrecto: "Incorrecto. No estamos aumentando la energía.",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "300",
        "15",
        "300",
        "100",
        "300",
        "4500",
        "100",
        "300",
        "45",
        "255",
      ],
    },
  },
  {
    id: 3,
    enunciado:
      "En una partida de Brawl Stars he perdido un 10% de los puntos de vida que tenía. Si tenía 250, ¿cuántos tengo ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars he <span style="color: red;">PERDIDO</span> un <span style="color: red;">10%</span> de los puntos de vida que <span style="color: red;">tenía</span>. Si tenía <span style="color: red;">250</span>, ¿cuántos tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "Correcto! No podemos hacer sólo una regla de 3",
      feedbackIncorrecto: "Incorrecto! Hay porcentaje, hay fórmula de Fran",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "Correcto",
      feedbackIncorrecto: "Incorrecto",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Disminución",
      respuestaIncorrecta: "Aumento",
      feedbackCorrecto: "Correcto",
      feedbackIncorrecto: "Incorrecto. Vamos a aumentar lo que ya teníamos",
    },
    fórmula: {
      formulaType: "disminución",
      respuestaCorrecta: [
        "250",
        "10",
        "250",
        "100",
        "250",
        "2500",
        "100",
        "250",
        "25",
        "225",
      ],
    },
  },
  {
    id: 1,
    enunciado:
      "Una partida de Brawl me ha generado un 20% de gemas más de las que tenía. Si tenía 25 gemas, ¿cuántas tengo ahora?",
    enunciadoFeedback: `Una partida de Brawl me ha generado un <span style="color: red;">20%</span> de gemas <span style="color: red;">MÁS</span> de las que <span style="color: red;">tenía</span>. Si tenía 25 gemas, ¿cuántas tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "Correcto! No podemos hacer sólo una regla de 3",
      feedbackIncorrecto: "Incorrecto! Hay porcentaje, hay fórmula de Fran",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "Correcto",
      feedbackIncorrecto: "Incorrecto",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Aumento",
      respuestaIncorrecta: "Disminución",
      feedbackCorrecto: "Correcto",
      feedbackIncorrecto: "Incorrecto. Vamos a aumentar lo que ya teníamos",
    },
    fórmula: {
      formulaType: "aumento",
      respuestaCorrecta: [
        "25",
        "20",
        "25",
        "100",
        "25",
        "500",
        "100",
        "25",
        "5",
        "30",
      ],
    },
  },
  {
    id: 10,
    enunciado:
      "En una partida de Brawl Stars, he conseguido un 15% más de monedas de las que tenía. Si tenía 80 monedas, ¿cuántas tengo ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, he conseguido un <span style="color: red;">15%</span> más de monedas de las que <span style="color: red;">tenía</span>. Si tenía <span style="color: red;">80</span> monedas, ¿cuántas tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! Necesitamos calcular el aumento.",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay un aumento de monedas.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Aumento",
      respuestaIncorrecta: "Disminución",
      feedbackCorrecto: "¡Correcto! Vamos a aumentar lo que ya teníamos.",
      feedbackIncorrecto: "Incorrecto. No estamos disminuyendo.",
    },
    fórmula: {
      formulaType: "aumento",
      respuestaCorrecta: [
        "80",
        "15",
        "80",
        "100",
        "80",
        "1200",
        "100",
        "80",
        "12",
        "92",
      ],
    },
  },
  {
    id: 11,
    enunciado:
      "En una partida de Brawl Stars, he ganado un 25% más de puntos de experiencia. Si tenía 200 puntos de experiencia, ¿cuántos tengo ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, he ganado un <span style="color: red;">25%</span> más de puntos de experiencia de los que <span style="color: red;">tenía</span>. Si tenía <span style="color: red;">200</span> puntos de experiencia, ¿cuántos tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! Necesitamos calcular el aumento.",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay un aumento de experiencia.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Aumento",
      respuestaIncorrecta: "Disminución",
      feedbackCorrecto: "¡Correcto! Vamos a aumentar lo que ya teníamos.",
      feedbackIncorrecto: "Incorrecto. No estamos disminuyendo.",
    },
    fórmula: {
      formulaType: "aumento",
      respuestaCorrecta: [
        "200",
        "25",
        "200",
        "100",
        "200",
        "5000",
        "100",
        "200",
        "50",
        "250",
      ],
    },
  },
  {
    id: 12,
    enunciado:
      "En una partida de Brawl Stars, he obtenido un 10% más de salud. Si tenía 1500 de salud, ¿cuánta salud tengo ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, he obtenido un <span style="color: red;">10%</span> más de salud de la que <span style="color: red;">tenía</span>. Si tenía <span style="color: red;">1500</span> de salud, ¿cuánta salud tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! Necesitamos calcular el aumento.",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay un aumento de salud.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Aumento",
      respuestaIncorrecta: "Disminución",
      feedbackCorrecto: "¡Correcto! Vamos a aumentar lo que ya teníamos.",
      feedbackIncorrecto: "Incorrecto. No estamos disminuyendo.",
    },
    fórmula: {
      formulaType: "aumento",
      respuestaCorrecta: [
        "1500",
        "10",
        "1500",
        "100",
        "1500",
        "15000",
        "100",
        "1500",
        "150",
        "1650",
      ],
    },
  },
  {
    id: 13,
    enunciado:
      "En una partida de Brawl Stars, he conseguido un 30% más de poder de ataque. Si tenía 400 de poder de ataque, ¿cuánto poder de ataque tengo ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, he conseguido un <span style="color: red;">30%</span> más de poder de ataque de lo que <span style="color: red;">tenía</span>. Si tenía <span style="color: red;">400</span> de poder de ataque, ¿cuánto poder de ataque tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! Necesitamos calcular el aumento.",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay un aumento de poder de ataque.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Aumento",
      respuestaIncorrecta: "Disminución",
      feedbackCorrecto: "¡Correcto! Vamos a aumentar lo que ya teníamos.",
      feedbackIncorrecto: "Incorrecto. No estamos disminuyendo.",
    },
    fórmula: {
      formulaType: "aumento",
      respuestaCorrecta: [
        "400",
        "30",
        "400",
        "100",
        "400",
        "12000",
        "100",
        "400",
        "120",
        "520",
      ],
    },
  },
  {
    id: 14,
    enunciado:
      "En una partida de Brawl Stars, he ganado un 50% más de tiempo de juego. Si tenía 60 minutos, ¿cuánto tiempo tengo ahora?",
    enunciadoFeedback: `En una partida de Brawl Stars, he ganado un <span style="color: red;">50%</span> más de tiempo de juego de lo que <span style="color: red;">tenía</span>. Si tenía <span style="color: red;">60</span> minutos, ¿cuánto tiempo tengo <span style="color: red;">ahora</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto! Necesitamos calcular el aumento.",
      feedbackIncorrecto:
        "Incorrecto. Hay un porcentaje que debemos considerar.",
    },
    p2: {
      enunciado: "¿Hay algún aumento o disminución?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "¡Correcto!",
      feedbackIncorrecto: "Incorrecto. Hay un aumento de tiempo de juego.",
    },
    p3: {
      enunciado: "¿Es un aumento o una disminución?",
      respuestaCorrecta: "Aumento",
      respuestaIncorrecta: "Disminución",
      feedbackCorrecto: "¡Correcto! Vamos a aumentar lo que ya teníamos.",
      feedbackIncorrecto: "Incorrecto. No estamos disminuyendo.",
    },
    fórmula: {
      formulaType: "aumento",
      respuestaCorrecta: [
        "60",
        "50",
        "60",
        "100",
        "60",
        "3000",
        "100",
        "60",
        "30",
        "90",
      ],
    },
  },
  {
    id: 2,
    enunciado:
      "Un estudiante ha sacado 85 puntos sobre un total de 90 en un examen. ¿Cuánto sería su calificación si el examen se hubiera realizado sobre 10 puntos?",
    enunciadoFeedback: `Un estudiante ha sacado 85 <span style="color: red;">puntos</span> sobre un <span style="color: red;">total</span> de 90 en un examen. ¿Cuánto sería su calificación si el examen se hubiera realizado sobre 10 <span style="color: red;">puntos</span>?`,
    p1: {
      enunciado: "¿Es un problema de porcentajes?",
      respuestaCorrecta: "No",
      respuestaIncorrecta: "Sí",
      feedbackCorrecto: "Entonces, vamos a hacer la regla de 3",
      feedbackIncorrecto: "No hay ningún %. Vamos a hacer una regla de 3",
    },
    p2: {
      enunciado: "¿Es proporcionalidad directa?",
      respuestaCorrecta: "Sí",
      respuestaIncorrecta: "No",
      feedbackCorrecto: "Correcto",
      feedbackIncorrecto:
        "Incorrecto. Cuanto más subimos la nota máxima, más sube la nota sacada",
    },
    fórmula: {
      formulaType: "regla3",
      respuestaCorrecta: [
        "85",
        "90",
        "x",
        "10",
        "850",
        "90",
        "850",
        "90",
        "9.44",
      ],
    },
  },
];

export default questions;
